-- 코드를 작성해주세요
SELECT C.ID AS ID
FROM ECOLI_DATA AS C
INNER JOIN 
(SELECT C.ID,
 C.PARENT_ID
FROM ECOLI_DATA AS C
INNER JOIN ECOLI_DATA AS P
ON C.PARENT_ID = P.ID
WHERE P.PARENT_ID IS NULL) AS P
ON C.PARENT_ID = P.ID
WHERE P.PARENT_ID IS NOT NULL
ORDER BY C.ID ASC;